routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RecruitmentController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Auth::routes();

Route::get('auth/admin/login', [
    'as' => 'login',
    'uses' => 'Auth\LoginController@showLoginForm'
]);
Route::post('auth/admin/login', [
    'as' => '',
    'uses' => 'Auth\LoginController@login'
]);
Route::get('auth/admin/logout', [
    'as' => 'logout',
    'uses' => 'Auth\LoginController@logout'
]);
// Route::get('auth/admin/register', [
//     'as' => 'register',
//     'uses' => 'Auth\RegisterController@showRegistrationForm'
// ]);
// Route::post('auth/admin/register', [
//     'as' => '',
//     'uses' => 'Auth\RegisterController@register'
// ]);

Route::get('/', 'HomeController@index')->name('landing');
Route::get('regulation', 'HomeController@regulation')->name('regulation');
Route::get('blog', 'HomeController@blog')->name('blog');
Route::get('recruitment', [HomeController::class, 'recruitment'])->name('recruitment');
Route::get('blog/search', 'HomeController@blogsearch')->name('blog.search');
Route::get('blog/detail/{slug}', 'HomeController@blogdetail')->name('blog.detail');
Route::get('blog/categories/{slug}', 'HomeController@blogcategories')->name('blog.categories');
Route::get('admin/dashboard', 'AdminController@dashboard')->name('dashboard');
Route::get('admin/settings', 'AdminController@settings')->name('settings');
Route::post('admin/settings', 'AdminController@settings_save')->name('settings.save');


Route::resource('admin/posts', 'PostController', ['names' => 'posts']);
Route::resource('admin/categories', 'CategoryController', ['names' => 'categories']);
Route::resource('admin/regulations', 'RegulationController', ['names' => 'regulations']);

Route::prefix('admin/recruitment')->group(function () {
    Route::get('/', [RecruitmentController::class, 'index']);
});

Route::prefix("admin/category-recruitment")->group(function () {
    Route::get('/', [RecruitmentController::class, 'category']);
    Route::get('/create', [RecruitmentController::class, 'categoryPage']);
    Route::post('/store', [RecruitmentController::class, 'categoryStore']);
    Route::get('/create', [RecruitmentController::class, 'categoryPage']);
});

Route::post('ckeditor/upload', 'PostController@ckeditor')->name('ckeditor.upload');

Route::post('blog/comments/post/{id}', 'CommentController@store')->name('comments.store');
// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Regulation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Regulation extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'year',
        'type',
        'entity',
        'file',
    ];
}

app/Http/Controllers/RegulationController.php
<?php

namespace App\Http\Controllers;

use App\Models\Regulation;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use Auth;

class RegulationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        //
        $data['regulations'] = Regulation::all();
        return view("pages.back.regulation.index", $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('pages.back.regulation.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validator = Validator::make($request->all(), [
            "title" => "required",
            "year" => "required",
            "type" => "required",
            "entity" => "required",
            "file" => "required|mimes:pdf|max:10000",
        ]);

        $fileName = null;

        if($request->hasFile('file')) {
            $originName = $request->file('file')->getClientOriginalName();
            $fileName = pathinfo($originName, PATHINFO_FILENAME);
            $extension = $request->file('file')->getClientOriginalExtension();
            $fileName = $fileName.'_'.time().'.'.$extension;
        
            $request->file('file')->move(public_path('files'), $fileName);
   
            $CKEditorFuncNum = $request->input('CKEditorFuncNum');
            $url = asset('files/'.$fileName); 
            $msg = 'Image uploaded successfully'; 
        }

        $input = array_merge($request->except('_token'), ['file' => $fileName]);

        $regulations = Regulation::insert($input);
        return redirect()->route('regulations.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Regulation  $regulation
     * @return \Illuminate\Http\Response
     */
    public function show(Regulation $regulation)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Regulation  $regulation
     * @return \Illuminate\Http\Response
     */
    public function edit(Regulation $regulation)
    {
        //
        $data['regulation'] = Regulation::findOrFail($regulation->id);
        return view('pages.back.regulation.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Regulation  $regulation
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Regulation $regulation)
    {
        //
        $validator = Validator::make($request->all(), [
            "title" => "required",
            "year" => "required",
            "type" => "required",
            "entity" => "required",
            "file" => "required|mimes:pdf|max:10000",
        ]);

        $input = $request->except(['_token', '_method']);

        if($request->hasFile('file')) {
            $originName = $request->file('file')->getClientOriginalName();
            $fileName = pathinfo($originName, PATHINFO_FILENAME);
            $extension = $request->file('file')->getClientOriginalExtension();
            $fileName = $fileName.'_'.time().'.'.$extension;
        
            $request->file('file')->move(public_path('files'), $fileName);
   
            $CKEditorFuncNum = $request->input('CKEditorFuncNum');
            $url = asset('files/'.$fileName); 
            $msg = 'Image uploaded successfully'; 

            $input = array_merge($input, ['file' => $fileName]);
        }

        $regulations = Regulation::findOrFail($regulation->id)->update($input);
        return redirect()->route('regulations.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Regulation  $regulation
     * @return \Illuminate\Http\Response
     */
    public function destroy(Regulation $regulation)
    {
        //
        $delete = Regulation::findOrFail($regulation->id)->delete();
        return redirect()->route('regulations.index');
    }
}

resources/views/pages/back/regulation/add.blade.php
@extends('layouts.app')

@section('custom-style')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.css"/>
<style>
    .ck-editor__editable {
        min-height: 200px;
    }
    .bootstrap-tagsinput input{
        min-width: 40vh;
        padding-top: 4px;
        padding-bottom: 5px;
    }
</style>
@endsection

@section('content')
<!-- <script src="https://cdn.ckeditor.com/ckeditor5/32.0.0/classic/ckeditor.js"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.9.2/ckeditor.js"></script>
<script src="https://cdn.jsdelivr.net/npm/grapesjs-plugin-ckeditor@0.0.9/dist/grapesjs-plugin-ckeditor.min.js"></script>
<div class="container">
    <div class="row">
        @include("includes.back.menus")
        <div class="col-lg-9 col-md-12 mb-2">
            <div class="card">
                <div class="card-body">
                    <h4 class="mb-4">Add New Regulation</h4>
                    <form action="{{ route('regulations.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group mb-2">
                            <label for="title" class="mb-2">Title</label>
                            <input type="text" placeholder="Type the Title" required="" name="title" class="form-control">
                        </div>
                        <div class="form-group mb-2">
                            <label for="title" class="mb-2">Year</label>
                            <input type="number" placeholder="Type the Year" required="" name="year" class="form-control">
                        </div>
                        <div class="form-group mb-2">
                            <label for="title" class="mb-2">Type</label>
                            <input type="text" placeholder="Type the Type" required="" name="type" class="form-control">
                        </div>
                        <div class="form-group mb-2">
                            <label for="entity" class="mb-2">Entity</label>
                            <input type="text" placeholder="Type the Entity" required="" name="entity" class="form-control">
                        </div>
                        <div class="form-group mb-2">
                            <label for="file" class="mb-2">File</label>
                            <input type="file" placeholder="Type the Title" required="" name="file" accept="application/pdf" class="form-control">
                        </div>
                        <div class="form-group mb-2">
                            <button type="submit" class="btn btn-primary mt-2">
                                <i class="fa fa-check me-2"></i>
                                Save
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    CKEDITOR.replace('content', {
        filebrowserUploadUrl: "{{route('ckeditor.upload', ['_token' => csrf_token() ])}}",
        filebrowserUploadMethod: 'form',
    });
</script>
@endsection

@section('custom-script')
<script src="{{ asset('js/bootstrap-tag.js') }}"></script>
@endsection

resources/views/pages/back/regulation/edit.blade.php
@extends('layouts.app')

@section('custom-style')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.css"/>
<style>
    .ck-editor__editable {
        min-height: 200px;
    }
    .bootstrap-tagsinput input{
        min-width: 40vh;
        padding-top: 4px;
        padding-bottom: 5px;
    }
</style>
@endsection

@section('content')
<!-- <script src="https://cdn.ckeditor.com/ckeditor5/32.0.0/classic/ckeditor.js"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.9.2/ckeditor.js"></script>
<script src="https://cdn.jsdelivr.net/npm/grapesjs-plugin-ckeditor@0.0.9/dist/grapesjs-plugin-ckeditor.min.js"></script>
<div class="container">
    <div class="row">
        @include("includes.back.menus")
        <div class="col-lg-9 col-md-12 mb-2">
            <div class="card">
                <div class="card-body">
                    <h4 class="mb-4">Edit Regulation</h4>
                    <form action="{{ route('regulations.update', [$regulation->id]) }}" method="post" enctype="multipart/form-data">
                        @method('patch')
                        @csrf
                        <div class="form-group mb-2">
                            <label for="title" class="mb-2">Title</label>
                            <input type="text" placeholder="Type the Title" required="" name="title" class="form-control" value="{{ $regulation->title }}">
                        </div>
                        <div class="form-group mb-2">
                            <label for="title" class="mb-2">Year</label>
                            <input type="number" placeholder="Type the Year" required="" name="year" class="form-control" value="{{ $regulation->year }}">
                        </div>
                        <div class="form-group mb-2">
                            <label for="title" class="mb-2">Type</label>
                            <input type="text" placeholder="Type the Type" required="" name="type" class="form-control" value="{{ $regulation->type }}">
                        </div>
                        <div class="form-group mb-2">
                            <label for="entity" class="mb-2">Entity</label>
                            <input type="text" placeholder="Type the Entity" required="" name="entity" class="form-control" value="{{ $regulation->entity }}">
                        </div>
                        <div class="form-group mb-2">
                            <label for="file" class="mb-2">File</label>
                            <input type="file" placeholder="Type the Title" name="file" accept="application/pdf" class="form-control">
                        </div>
                        <div class="form-group mb-2">
                            <button type="submit" class="btn btn-primary mt-2">
                                <i class="fa fa-check me-2"></i>
                                Save
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    CKEDITOR.replace('content', {
        filebrowserUploadUrl: "{{route('ckeditor.upload', ['_token' => csrf_token() ])}}",
        filebrowserUploadMethod: 'form',
    });
</script>
@endsection

@section('custom-script')
<script src="{{ asset('js/bootstrap-tag.js') }}"></script>
@endsection

resources/views/pages/back/regulation/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        @include("includes.back.menus")
        <div class="col-lg-9 col-md-12 mb-2">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex flex-row justify-content-between">
                        <h4 class="mb-4">Data Regulation</h4>
                        <a href="{{ route('regulations.create') }}">
                            <button type="button" class="btn btn-success">
                                <i class="fa fa-plus me-2"></i>
                                Add new
                            </button>
                        </a>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Title</th>
                                    <th>Year</th>
                                    <th>Type</th>
                                    <th>Entity</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($regulations as $key => $regulation)
                                <tr>
                                    <td>{{ $key + 1 }}</td>
                                    <td><b>{{ $regulation->title }}</b></td>
                                    <td>{{ $regulation->year }}</td>
                                    <td>{{ $regulation->type }}</td>
                                    <td>{{ $regulation->entity }}</td>
                                    <td>
                                        <div class="d-flex flex-row">
                                            <a href="{{ asset('public/files/'.$regulation->file) }}" class="me-2">
                                                <button class="btn btn-sm btn-primary">
                                                    <i class="fa fa-download"></i>
                                                </button>
                                            </a>
                                            <a href="{{ route('regulations.edit', [$regulation->id]) }}" class="me-2">
                                                <button class="btn btn-sm btn-warning text-dark">
                                                    <i class="fa fa-cog"></i>
                                                </button>
                                            </a>
                                            <form method="post" action="{{ route('regulations.destroy', [$regulation->id]) }}">
                                                @method('delete')
                                                @csrf
                                                <button type="submit" class="btn btn-sm btn-danger">
                                                    <i class="fa fa-times mx-1"></i>
                                                </button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach

                                @if(count($regulations) == 0)
                                <tr>
                                    <td colspan="6" class="text-center">
                                        <b>There is nothing here.</b>
                                    </td>
                                </tr>
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection