routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RecruitmentController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Auth::routes();

Route::get('auth/admin/login', [
    'as' => 'login',
    'uses' => 'Auth\LoginController@showLoginForm'
]);
Route::post('auth/admin/login', [
    'as' => '',
    'uses' => 'Auth\LoginController@login'
]);
Route::get('auth/admin/logout', [
    'as' => 'logout',
    'uses' => 'Auth\LoginController@logout'
]);
// Route::get('auth/admin/register', [
//     'as' => 'register',
//     'uses' => 'Auth\RegisterController@showRegistrationForm'
// ]);
// Route::post('auth/admin/register', [
//     'as' => '',
//     'uses' => 'Auth\RegisterController@register'
// ]);

Route::get('/', 'HomeController@index')->name('landing');
Route::get('regulation', 'HomeController@regulation')->name('regulation');
Route::get('blog', 'HomeController@blog')->name('blog');
Route::get('recruitment', [HomeController::class, 'recruitment'])->name('recruitment');
Route::get('blog/search', 'HomeController@blogsearch')->name('blog.search');
Route::get('blog/detail/{slug}', 'HomeController@blogdetail')->name('blog.detail');
Route::get('blog/categories/{slug}', 'HomeController@blogcategories')->name('blog.categories');
Route::get('admin/dashboard', 'AdminController@dashboard')->name('dashboard');
Route::get('admin/settings', 'AdminController@settings')->name('settings');
Route::post('admin/settings', 'AdminController@settings_save')->name('settings.save');


Route::resource('admin/posts', 'PostController', ['names' => 'posts']);
Route::resource('admin/categories', 'CategoryController', ['names' => 'categories']);
Route::resource('admin/regulations', 'RegulationController', ['names' => 'regulations']);

Route::prefix('admin/recruitment')->group(function () {
    Route::get('/', [RecruitmentController::class, 'index']);
});

Route::prefix("admin/category-recruitment")->group(function () {
    Route::get('/', [RecruitmentController::class, 'category']);
    Route::get('/create', [RecruitmentController::class, 'categoryPage']);
    Route::post('/store', [RecruitmentController::class, 'categoryStore']);
    Route::get('/create', [RecruitmentController::class, 'categoryPage']);
});

Route::post('ckeditor/upload', 'PostController@ckeditor')->name('ckeditor.upload');

Route::post('blog/comments/post/{id}', 'CommentController@store')->name('comments.store');
// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    public function user(){
        return $this->belongsTo('App\Models\User');
    }

    public function category(){
        return $this->belongsTo('App\Models\Category');
    }

    public function tags(){
        return $this->hasMany('App\Models\Tag', 'post_id', 'id');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use Auth;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function ckeditor(Request $request)
    {
        if($request->hasFile('upload')) {
            $originName = $request->file('upload')->getClientOriginalName();
            $fileName = pathinfo($originName, PATHINFO_FILENAME);
            $extension = $request->file('upload')->getClientOriginalExtension();
            $fileName = $fileName.'_'.time().'.'.$extension;
        
            $request->file('upload')->move('images', $fileName);
   
            $CKEditorFuncNum = $request->input('CKEditorFuncNum');
            $url = asset('images/'.$fileName); 
            $msg = 'Image uploaded successfully '.$url; 
            $response = "<script>window.parent.CKEDITOR.tools.callFunction($CKEditorFuncNum, '$url', '$msg')</script>";
               
            @header('Content-type: text/html; charset=utf-8'); 
            echo $response;
        }
    }
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        //
        $data['posts'] = Post::orderBy('created_at', 'DESC')->get();
        return view("pages.back.posts.index", $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $data['categories'] = Category::all();
        return view('pages.back.posts.add', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validator = Validator::make($request->all(), [
            "title" => "required",
            "keywords" => "required",
            "category_id" => "required|integer",
            "thumbnail" => "required",
            "file" => "required|mimes:jpg,png,jpeg|max:10000"
        ]);

        if($request->hasFile('file')) {
            $originName = $request->file('file')->getClientOriginalName();
            $fileName = pathinfo($originName, PATHINFO_FILENAME);
            $extension = $request->file('file')->getClientOriginalExtension();
            $fileName = $fileName.'_'.time().'.'.$extension;
        
            $request->file('file')->move('images/thumbnail', $fileName);
   
            $CKEditorFuncNum = $request->input('CKEditorFuncNum');
            $url = asset('images/thumbnail/'.$fileName); 
            $msg = 'Image uploaded successfully'; 
        }

        $post = new Post;
        $post->title = $request->title;
        $post->user_id = Auth::user()->id;
        $post->slug = Str::slug($request->title);
        $post->keywords = $request->keywords;
        $post->content = $request->content;
        $post->thumbnail = $fileName;
        $post->category_id = $request->category_id;
        $post->save();

        return redirect()->route('posts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $data['categories'] = Category::all();
        $data['post'] = $post;
        return view('pages.back.posts.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        //
        $rules = [
            "title" => "required",
            "keywords" => "required",
            "category_id" => "required|integer",
            "thumbnail" => "required",
        ];

        if($request->hasFile('file')) {
            $rules['file'] = "required|mimes:jpg,png,jpeg|max:10000";
        }

        $validator = Validator::make($request->all(), $rules);

        

        $update = Post::find($post->id);

        if($request->hasFile('file')) {
            $originName = $request->file('file')->getClientOriginalName();
            $fileName = pathinfo($originName, PATHINFO_FILENAME);
            $extension = $request->file('file')->getClientOriginalExtension();
            $fileName = $fileName.'_'.time().'.'.$extension;
        
            $request->file('file')->move('images/thumbnail', $fileName);
   
            $CKEditorFuncNum = $request->input('CKEditorFuncNum');
            $url = asset('images/thumbnail/'.$fileName); 
            $msg = 'Image uploaded successfully'; 

            $update->thumbnail = $fileName;
        }
        
        $update->title = $request->title;
        $update->slug = Str::slug($request->title);
        $update->keywords = $request->keywords;
        $update->content = $request->content;
        $update->category_id = $request->category_id;
        $update->save();

        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        //
        $delete = Post::findOrFail($post->id)->delete();
        return redirect()->route('posts.index');
    }
}

resources/views/pages/back/posts/add.blade.php
@extends('layouts.app')

@section('custom-style')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.css"/>
<style>
    .ck-editor__editable {
        min-height: 200px;
    }
    .bootstrap-tagsinput input{
        min-width: 40vh;
        padding-top: 4px;
        padding-bottom: 5px;
    }
</style>
@endsection

@section('content')
<!-- <script src="https://cdn.ckeditor.com/ckeditor5/32.0.0/classic/ckeditor.js"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.9.2/ckeditor.js"></script>
<script src="https://cdn.jsdelivr.net/npm/grapesjs-plugin-ckeditor@0.0.9/dist/grapesjs-plugin-ckeditor.min.js"></script>
<div class="container">
    <div class="row">
        @include("includes.back.menus")
        <div class="col-lg-9 col-md-12 mb-2">
            <div class="card">
                <div class="card-body">
                    <h4 class="mb-4">Add New Post</h4>
                    <form action="{{ route('posts.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group mb-2">
                            <label for="title" class="mb-2">Title</label>
                            <input type="text" placeholder="Title" required="" name="title" class="form-control">
                        </div>
                        <div class="form-group mb-2">
                            <label for="category" class="mb-2">Category</label>
                            <select name="category_id" class="form-control">
                                @foreach($categories as $key => $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group mb-2">
                            <label for="thumbnail" class="mb-2">Thumbnail</label>
                            <input type="file" required="" name="file" class="form-control">
                        </div>
                        <div class="form-group mb-2">
                            <label for="keywords" class="mb-2">Keywords</label><br>
                            <input type="text" name="keywords" class="form-control" data-role="tagsinput" placeholder="Type & Hit enter to append keywords">
                        </div>
                        <div class="form-group mb-2 mt-2">
                            <label for="content" class="mb-2">Content</label>
                            <textarea name="content" id="content" class="form-control" rows="5" placeholder="Content goes here.."></textarea>
                        </div>
                        <div class="form-group mb-2">
                            <button type="submit" class="btn btn-primary mt-2">
                                <i class="fa fa-check me-2"></i>
                                Save
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    CKEDITOR.replace('content', {
        filebrowserUploadUrl: "{{route('ckeditor.upload', ['_token' => csrf_token() ])}}",
        filebrowserUploadMethod: 'form',
    });
</script>
@endsection

@section('custom-script')
<script src="{{ asset('js/bootstrap-tag.js') }}"></script>
@endsection

resources/views/pages/back/posts/edit.blade.php
@extends('layouts.app')


@section('custom-style')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.css"/>
<style>
    .ck-editor__editable {
        min-height: 200px;
    }
    .bootstrap-tagsinput input{
        min-width: 40vh;
        padding-top: 4px;
        padding-bottom: 5px;
    }
</style>
@endsection

@section('content')

<!-- <script src="https://cdn.ckeditor.com/ckeditor5/32.0.0/classic/ckeditor.js"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.9.2/ckeditor.js"></script>
<script src="https://cdn.jsdelivr.net/npm/grapesjs-plugin-ckeditor@0.0.9/dist/grapesjs-plugin-ckeditor.min.js"></script>
<div class="container">
    <div class="row">
        @include("includes.back.menus")
        <div class="col-lg-9 col-md-12 mb-2">
            <div class="card">
                <div class="card-body">
                    <h4 class="mb-4">Edit Post</h4>
                    <form action="{{ route('posts.update', [$post->id]) }}" method="post" enctype="multipart/form-data">
                        @method('patch')
                        @csrf
                        <div class="form-group mb-2">
                            <label for="title" class="mb-2">Title</label>
                            <input type="text" placeholder="Title" required="" name="title" class="form-control" value="{{ $post->title }}">
                        </div>
                        <div class="form-group mb-2">
                            <label for="category" class="mb-2">Category</label>
                            <select name="category_id" class="form-control">
                                @foreach($categories as $key => $category)
                                <option value="{{ $category->id }}" {{ ($category->id == $post->category_id) ? 'selected' : '' }}>{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group mb-2">
                            <label for="thumbnail" class="mb-2">Thumbnail</label>
                            <input type="file" name="file" class="form-control">
                        </div>
                        <div class="form-group mb-2">
                            <label for="keywords" class="mb-2">Keywords</label><br>
                            <input type="text" name="keywords" class="form-control" data-role="tagsinput" placeholder="Type & Hit enter to append keywords" value="{{ $post->keywords }}">
                            <!-- <textarea name="keywords" class="form-control" rows="3" placeholder="keyword 1, keyword 2, keyword 3, etc..">{{ $post->keywords }}</textarea> -->
                        </div>
                        <div class="form-group mb-2">
                            <label for="content" class="mb-2">Content</label>
                            <textarea name="content" id="content" class="form-control" rows="5" placeholder="Content goes here..">{{ $post->content }}</textarea>
                        </div>
                        <div class="form-group mb-2">
                            <button type="submit" class="btn btn-primary mt-2">
                                <i class="fa fa-check me-2"></i>
                                Save
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    CKEDITOR.replace('content', {
        filebrowserUploadUrl: "{{route('ckeditor.upload', ['_token' => csrf_token() ])}}",
        filebrowserUploadMethod: 'form'
    });
</script>
@endsection

@section('custom-script')
<script src="{{ asset('js/bootstrap-tag.js') }}"></script>
@endsection

resources/views/pages/back/posts/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        @include("includes.back.menus")
        <div class="col-lg-9 col-md-12 mb-2">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex flex-row justify-content-between">
                        <h4 class="mb-4">Data Posts</h4>
                        <a href="{{ route('posts.create') }}">
                            <button type="button" class="btn btn-success">
                                <i class="fa fa-plus me-2"></i>
                                Add new
                            </button>
                        </a>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered" id="table">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Title</th>
                                    <th>Slug</th>
                                    <th>Keywords</th>
                                    <th>Visited</th>
                                    <th>Created at</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($posts as $key => $post)
                                <tr>
                                    <td>{{ $key + 1 }}</td>
                                    <td><b>{{ $post->title }}</b></td>
                                    <td><small>{{ $post->slug }}</small></td>
                                    <td>{{ $post->keywords }}</td>
                                    <td><small><b>{{ $post->visited }}</b> times</small></td>
                                    <td><small>{{ dateID($post->created_at) }}</small></td>
                                    <td>
                                        <div class="d-flex flex-row">
                                            <a href="{{ route('blog.detail', [$post->slug]) }}" class="me-2" target="_blank">
                                                <button class="btn btn-sm btn-primary">
                                                    <i class="fa fa-eye"></i>
                                                </button>
                                            </a>
                                            <a href="{{ route('posts.edit', [$post->id]) }}" class="me-2">
                                                <button class="btn btn-sm btn-warning text-dark">
                                                    <i class="fa fa-cog"></i>
                                                </button>
                                            </a>
                                            <form method="post" action="{{ route('posts.destroy', [$post->id]) }}">
                                                @method('delete')
                                                @csrf
                                                <button type="submit" class="btn btn-sm btn-danger">
                                                    <i class="fa fa-times mx-1"></i>
                                                </button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach

                                @if(count($posts) == 0)
                                <tr>
                                    <td colspan="6" class="text-center">
                                        <b>There is nothing here.</b>
                                    </td>
                                </tr>
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection