routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RecruitmentController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Auth::routes();

Route::get('auth/admin/login', [
    'as' => 'login',
    'uses' => 'Auth\LoginController@showLoginForm'
]);
Route::post('auth/admin/login', [
    'as' => '',
    'uses' => 'Auth\LoginController@login'
]);
Route::get('auth/admin/logout', [
    'as' => 'logout',
    'uses' => 'Auth\LoginController@logout'
]);
// Route::get('auth/admin/register', [
//     'as' => 'register',
//     'uses' => 'Auth\RegisterController@showRegistrationForm'
// ]);
// Route::post('auth/admin/register', [
//     'as' => '',
//     'uses' => 'Auth\RegisterController@register'
// ]);

Route::get('/', 'HomeController@index')->name('landing');
Route::get('regulation', 'HomeController@regulation')->name('regulation');
Route::get('blog', 'HomeController@blog')->name('blog');
Route::get('recruitment', [HomeController::class, 'recruitment'])->name('recruitment');
Route::get('blog/search', 'HomeController@blogsearch')->name('blog.search');
Route::get('blog/detail/{slug}', 'HomeController@blogdetail')->name('blog.detail');
Route::get('blog/categories/{slug}', 'HomeController@blogcategories')->name('blog.categories');
Route::get('admin/dashboard', 'AdminController@dashboard')->name('dashboard');
Route::get('admin/settings', 'AdminController@settings')->name('settings');
Route::post('admin/settings', 'AdminController@settings_save')->name('settings.save');


Route::resource('admin/posts', 'PostController', ['names' => 'posts']);
Route::resource('admin/categories', 'CategoryController', ['names' => 'categories']);
Route::resource('admin/regulations', 'RegulationController', ['names' => 'regulations']);

Route::prefix('admin/recruitment')->group(function () {
    Route::get('/', [RecruitmentController::class, 'index']);
});

Route::prefix("admin/category-recruitment")->group(function () {
    Route::get('/', [RecruitmentController::class, 'category']);
    Route::get('/create', [RecruitmentController::class, 'categoryPage']);
    Route::post('/store', [RecruitmentController::class, 'categoryStore']);
    Route::get('/create', [RecruitmentController::class, 'categoryPage']);
});

Route::post('ckeditor/upload', 'PostController@ckeditor')->name('ckeditor.upload');

Route::post('blog/comments/post/{id}', 'CommentController@store')->name('comments.store');
// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    
    public function posts(){
        return $this->hasMany('App\Models\Post', 'user_id', 'id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use Auth;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        //
        $data['categories'] = Category::all();
        return view("pages.back.category.index", $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('pages.back.category.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validator = Validator::make($request->all(), [
            "name" => "required",
        ]);

        $category = new Category;
        $category->name = $request->name;
		$category->template = $request->template;
        $category->slug = Str::slug($request->name);
        $category->save();

        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
        $data['category'] = Category::findOrFail($category->id);
        return view('pages.back.category.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
        $validator = Validator::make($request->all(), [
            "name" => "required",
        ]);

        $category = Category::findOrFail($category->id);
        $category->name = $request->name;
		$category->template = $request->template;
        $category->slug = Str::slug($request->name);
        $category->save();

        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
        $delete = Category::findOrFail($category->id)->delete();
        return redirect()->route('categories.index');
    }
}

resources/views/pages/back/category/add.blade.php
@extends('layouts.app')

@section('custom-style')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.css"/>
<style>
    .ck-editor__editable {
        min-height: 200px;
    }
    .bootstrap-tagsinput input{
        min-width: 40vh;
        padding-top: 4px;
        padding-bottom: 5px;
    }
</style>
@endsection

@section('content')
<!-- <script src="https://cdn.ckeditor.com/ckeditor5/32.0.0/classic/ckeditor.js"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.9.2/ckeditor.js"></script>
<script src="https://cdn.jsdelivr.net/npm/grapesjs-plugin-ckeditor@0.0.9/dist/grapesjs-plugin-ckeditor.min.js"></script>
<div class="container">
    <div class="row">
        @include("includes.back.menus")
        <div class="col-lg-9 col-md-12 mb-2">
            <div class="card">
                <div class="card-body">
                    <h4 class="mb-4">Add New Category</h4>
                    <form action="{{ route('categories.store') }}" method="post">
                        @csrf
                        <div class="form-group mb-2">
                            <label for="name" class="mb-2">Name</label>
                            <input type="text" placeholder="Name" required="" name="name" class="form-control">
                        </div>
                        <div class="form-group mb-2">
                            <label for="template" class="mb-2">Template</label>
                            <input type="text" placeholder="Template" required="" name="template" class="form-control">
                        </div>
                        <div class="form-group mb-2">
                            <button type="submit" class="btn btn-primary mt-2">
                                <i class="fa fa-check me-2"></i>
                                Save
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    CKEDITOR.replace('content', {
        filebrowserUploadUrl: "{{route('ckeditor.upload', ['_token' => csrf_token() ])}}",
        filebrowserUploadMethod: 'form',
    });
</script>
@endsection

@section('custom-script')
<script src="{{ asset('js/bootstrap-tag.js') }}"></script>
@endsection

resources/views/pages/back/category/edit.blade.php
@extends('layouts.app')

@section('custom-style')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.css"/>
<style>
    .ck-editor__editable {
        min-height: 200px;
    }
    .bootstrap-tagsinput input{
        min-width: 40vh;
        padding-top: 4px;
        padding-bottom: 5px;
    }
</style>
@endsection

@section('content')
<!-- <script src="https://cdn.ckeditor.com/ckeditor5/32.0.0/classic/ckeditor.js"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.9.2/ckeditor.js"></script>
<script src="https://cdn.jsdelivr.net/npm/grapesjs-plugin-ckeditor@0.0.9/dist/grapesjs-plugin-ckeditor.min.js"></script>
<div class="container">
    <div class="row">
        @include("includes.back.menus")
        <div class="col-lg-9 col-md-12 mb-2">
            <div class="card">
                <div class="card-body">
                    <h4 class="mb-4">Edit Category</h4>
                    <form action="{{ route('categories.update', [$category->id]) }}" method="post">
                        @method('patch')
                        @csrf
                        <div class="form-group mb-2">
                            <label for="name" class="mb-2">Name</label>
                            <input type="text" placeholder="Name" required="" name="name" class="form-control" value="{{ $category->name }}">
                        </div>
                        <div class="form-group mb-2">
                            <label for="template" class="mb-2">Template</label>
                            <input type="text" placeholder="Template" required="" name="template" class="form-control" value="{{ $category->template }}">
                        </div>
                        <div class="form-group mb-2">
                            <button type="submit" class="btn btn-primary mt-2">
                                <i class="fa fa-check me-2"></i>
                                Save
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    CKEDITOR.replace('content', {
        filebrowserUploadUrl: "{{route('ckeditor.upload', ['_token' => csrf_token() ])}}",
        filebrowserUploadMethod: 'form',
    });
</script>
@endsection

@section('custom-script')
<script src="{{ asset('js/bootstrap-tag.js') }}"></script>
@endsection

resources/views/pages/back/category/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        @include("includes.back.menus")
        <div class="col-lg-9 col-md-12 mb-2">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex flex-row justify-content-between">
                        <h4 class="mb-4">Data Categories</h4>
                        <a href="{{ route('categories.create') }}">
                            <button type="button" class="btn btn-success">
                                <i class="fa fa-plus me-2"></i>
                                Add new
                            </button>
                        </a>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Name</th>
                                    <th>Slug</th>
									<th>Template</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($categories as $key => $category)
                                <tr>
                                    <td>{{ $key + 1 }}</td>
                                    <td><b>{{ $category->name }}</b></td>
                                    <td><small><code>{{ $category->slug }}</code></small></td>
									<td><small><code>{{ $category->template }}</code></small></td>
                                    <td>
                                        <div class="d-flex flex-row">
                                            @if($category->slug !== null)
                                            <a href="{{ route('blog.categories', [$category->slug]) }}" class="me-2" target="_blank">
                                                <button class="btn btn-sm btn-primary">
                                                    <i class="fa fa-eye"></i>
                                                </button>
                                            </a>
                                            @endif
                                            <a href="{{ route('categories.edit', [$category->id]) }}" class="me-2">
                                                <button class="btn btn-sm btn-warning text-dark">
                                                    <i class="fa fa-cog"></i>
                                                </button>
                                            </a>
                                            <form method="post" action="{{ route('categories.destroy', [$category->id]) }}">
                                                @method('delete')
                                                @csrf
                                                <button type="submit" class="btn btn-sm btn-danger">
                                                    <i class="fa fa-times mx-1"></i>
                                                </button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach

                                @if(count($categories) == 0)
                                <tr>
                                    <td colspan="6" class="text-center">
                                        <b>There is nothing here.</b>
                                    </td>
                                </tr>
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection